# This workflow will install Python  run tests and lint with a single version of Pyth
name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
    - uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}
      #with:
       # python-version: "3.10"
       # cache: 'pip'
    - name: Install dependencies
      run: |
       pwd
       ls
     #  aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/phoenix-1708/DR_NED/resolve/main/checkpoints.zip -d checkpoints -o checkpoints.zip
     #   sudo apt-get update -y
      #  sudo apt-get install aria2 -y
       # cd preprocessing
        #python -m pip install --upgrade pip
        #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: python bot
      run: |
         python bot.py
   # - name: Test with pytest
    #  run: |
     #   pytest
