# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install aria2 -y
        pwd
        aria2c --console-log-level=error -c -x 16 -s 16 -k 1M https://huggingface.co/phoenix-1708/DR_NED/resolve/main/checkpoints.zip -d /home/runner/work/dn/checkpoints -o checkpoints.zip
        unzip /home/runner/work/dn/checkpoints/checkpoints.zip
        ls
        cp *.lib /home/runner/work/dn/checkpoints
        ls
        cd checkpoints
        ls
       # cd preprocessing
       # python -m pip install --upgrade pip
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        python bot.py
    - name: Test with pytest
      run: |
        pytest
